ModifiQApp.config(function($routeProvider, $locationProvider) {
    $routeProvider.when('/', {
        cache: false,
        templateUrl: 'views/login/login.html',
        controller: 'loginController'
    }).when('/dashboard', {
        cache: false,
        templateUrl: 'views/dashboard/dashboard.html',
        controller: 'dashboardController'
    }).when('/alunos', {
        cache: false,
        templateUrl: 'views/alunos/alunos.html',
        controller: 'alunosController'
    }).when('/alunos/detalhe/:id', {
        cache: false,
        templateUrl: 'views/alunos/detalhe.html',
        controller: 'alunoDetalheController'
    }).when('/alunos/registroevolutivo/:id', {
        cache: false,
        templateUrl: 'views/alunos/registroevolutivo.html',
        controller: 'registroEvolutivoController'
    }).when('/agenda', {
        cache: false,
        templateUrl: 'views/agenda/agenda.html',
        controller: 'agendaController'
    }).when('/contato', {
        url: '/contato',
        cache: false,
        templateUrl: 'views/contato/contato.html',
        controller: 'contatoController'
    }).otherwise({redirectTo: '/'});;
});